language: generic
sudo: required
branches:
  except:
    - /^v[0-9]*/
before_script:
- sudo add-apt-repository ppa:koffeinflummi/armake -y
- sudo apt-get update -y
- sudo apt-get install armake -y
script:
- export VERSION=`cat description.ext  | grep -o 'onLoadName = ".*"' | grep -o 'v[0-9.][0-9.]*'`
- armake build -w unquoted-string -w redefinition-wo-undef -w excessive-concatenation -x ".*" -x "*.pbo" -x "*.md" . 7Cav_FullSpectrum_$VERSION.Chernarus_Winter.pbo
- git tag $VERSION
deploy:
  if:
    branch: master
  provider: releases
  skip_cleanup: true
  file: '7Cav_FullSpectrum_$VERSION.Chernarus_Winter.pbo'
  on:
    branch: master
    repo: 7Cav/7Cav_FullSpectrum_V4.Chernarus_Winter
  name: '7th Cavalry Full Spectrum $VERSION - Chernarus_Winter'
  api_key:
    secure: K3evh2VGfdxS2psD+uLEAlGWc6SyvtWqL9DYcipGui2Pqq/EJ1+ourNJt+/1vwluWfoULC3Qc4/IzGNOeyWR0njfo4LDrx8UeB/PTuBfjpVGUeryvsM9TpukBDA7ZSVcE9x99g0P9rJXiH0/dOGJwudeCT7xmzJ3D2Tq3vmfRZchYo4Q5ADLxG0V32gOq2dqW4mAJR2LwXuzo1DvVOtX2LRHtOYCit1MRZtTAgPiej7WDw8efjY87cWNWMk8tgwPjZ6eVldkmnF8+g4gAllk7hKi5cL6qs/hWt09DGG602Yl4PYbZYi2nHjiirTju6sY62fZLUvY75Nogv8urM5r3MW81yWIJDMveU9MDkFcAHs6bkrqb/+TNQeEUefWbHE2WptQQuvzVpBxhOWjk/9NffC6N++Pn4iOP0EeCidvEf8uZjgJnkGQ6zGC0PEfz+GeR7cvBgSvIpR3drPLBvJ3nWj789HfQy4aWxXtDFvxSbGyx9DmUHa8bgf2gvkLbITlaAX1eQIdiPSoAa+xRJt1DutavDZg2ihnH1yTRWd1fjqYfwcX082wMqevi9B7KkPBQstVYjHf3zzBCxR0r8PAMpzoGw04NiwD0pehzOl7XSB7ZBVHZ8Gk0WugI89HY/djPu3APffyATyJeIZG3Q72EwMAsKEGQsPV1CVUVCVNcDU=
